### ISSUE TITLE
Fragment order with named fields returns invalid response

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#138] opened 2017-04-04 09:15 UTC
Query:
```
query Queries {
  viewer {
    me {
      profilePhotoAlbum {
        ...albumInfo
      }
      ...userInfo // <== POSITION OF THIS IS IMPORTANT
    }
  }
}
fragment userInfo on User {
  profilePhotoAlbum {
    p1: id
  }
}
fragment albumInfo on PhotoAlbum {
  p2: id
}
```
Result: 
```
{
  "data": {
    "viewer": {
      "me": {
        "profilePhotoAlbum": {
          "p1": "UGhvdG9BbGJ1bToxMDAwMjUwNg==" // <== MISSING p2
        }
      }
    }
  }
}
```

Second query with moved `userInfo` fragment up
```
query Queries {
  viewer {
    me {
      ...userInfo // <== POSITION OF THIS IS IMPORTANT
      profilePhotoAlbum {
        ...albumInfo
      }
    }
  }
}
fragment userInfo on User {
  profilePhotoAlbum {
    p1: id
  }
}
fragment albumInfo on PhotoAlbum {
  p2: id
}
```
Result: 
```
{
  "data": {
    "viewer": {
      "me": {
        "profilePhotoAlbum": {
          "p2": "UGhvdG9BbGJ1bToxMDAwMjUwNg==" // <== MISSING p1
        }
      }
    }
  }
}
```
Conclusion: Order of ragments contained named fields can cause invalid response. At both queries expected result was containing `p1` and `p2` but received only one. This problem is simplified as much as I can but can cause really big problems when used with relay

**Comment by Peping** [comment] 2017-08-17 12:33
I think the issue was caused by naively thinking that `array_merge`, used in collectResult, was merging the arrays recursively. It does not behave that way, but `array_replace_recursive` does. 

I used the `array_replace_recursive` function instead of `array_merge_recursive`, because it better mimics ES2015's object spread behavior. On top of that `array_merge_recursive`, without further processing, would break the result when requesting the same scalar field twice:
```graphql
query {
   Foo { id, name }
   Foo { id, price }
}
```

**Result with `array_merge_recursive`**:

```json
{ "data": { "Foo": { "id": [13, 13], "name":"Fizz", "price": 123}}}
``` 
**Result with `array_replace_recursive`**:
```json
{ "data": { "Foo": { "id": 13, "name":"Fizz", "price": 123}}}
```

**Comment by Peping** [comment] 2017-08-17 13:00
A potential issue with my current approach is what happens with lists. Consider the following query:
```graphql
query {
    TrainList(line: "R9") { name, line, company }
    TrainList(company: "North Rail") { name, line, company }
}
```
On their own, the lines generate these results:
```json
{ 
    "data":  [
        {"name": "Northern Express", "line": "R9", "company": "North Rail"}, 
        {"name": "Thomas", "line": "R9", "company": "Tank Engines Ltd."}, 
        {"name": "James", "line": "R9", "company": "Tank Engines Ltd."} 
    ]
}
```
and
```json
{ 
    "data":  [
        {"name": "Northern Express", "line": "R9", "company": "North Rail"}, 
        {"name": "Ivan", "line": "Transsib", "company": "North Rail"}
    ]
}
```
The issue is: **What merging strategy do we use now?**

**Result with `array_replace_recursive`**:
```json
{ 
    "data":  [
        {"name": "Northern Express", "line": "R9", "company": "North Rail"}, 
        {"name": "Thomas", "line": "R9", "company": "Tank Engines Ltd."}, 
        {"name": "James", "line": "R9", "company": "Tank Engines Ltd."},
        {"name": "Northern Express", "line": "R9", "company": "North Rail"}, 
        {"name": "Ivan", "line": "Transsib", "company": "North Rail"}
    ]
}
```

**Result with `array_merge_recursive`**:
```json
{ 
    "data":  [
        {"name": "Northern Express", "line": "R9", "company": "North Rail"}, 
        {"name": "Ivan", "line": "Transsib", "company": "North Rail"},
        {"name": "James", "line": "R9", "company": "Tank Engines Ltd."} 
    ]
}
```

Neither of these solutions are ideal.  I'm not sure how other libraries and frameworks deal with this. We should probably investigate this first.

**Comment by fritz-gerneth** [comment] 2017-08-17 14:01
Simply merging the result is the wrong approach for this problem. The [specification ](https://facebook.github.io/graphql/#sec-Field-Selection-Merging)is actually clear on how this scenario must be handled. They can only be merged if:

> fieldA and fieldB must have identical field names.
> fieldA and fieldB must have identical sets of arguments.

Also, this is a real merge of the two result sets, so objects returned from both fields would show up twice. Note that this does not apply for aliased fields / fields including fragments (they'd have a different name). 

I think the query would need to be flattened out before actually executing it. In the query, Inline fragments then would need to be merged into the query.

Flattening the initial query, it would read as:
```
query Queries {
  viewer {
    me {
      profilePhotoAlbum {
           p2: id
      }
      profilePhotoAlbum {
            p1: id
      }
    }
  }
}
```

So the expected result really would be 
```
viewer {
    me: {
        profilePhotoAlbum: [
            {p2: 'some-value'}
            {p2: 'some-value2'}
            {p2: 'some-value3'}
            {p1: 'some-value'}
            {p2: 'some-value2'}
            {p3: 'some-value3'}
        ]
    }
}
```
Just for an example - this would result in the field being accessed twice, and the results being merged as by the rules above. 

Note the restriction that this may only be merged if the arguments for that field are the same! If they are not we'd have to use aliases.

**Comment by Peping** [comment] 2017-08-17 15:59
Are you sure that's what the docs imply? That wouldn't be very useful. Besides, at least one other framework doesn't do it this way. 

Try **[this Apollo Launchpad](https://launchpad.graphql.com/1jzxrj179)** with the following query:
```graphql
query Posts {
    posts {
      title
      author {
        firstName
      }
    }
    posts {
      votes
      author {
        lastName
      }
    }
}
```
<details><summary>**Spoiler alert!** the result is not what you think. Click to view</summary>

```json
{
  "data": {
    "posts": [
      {
        "title": "Introduction to GraphQL",
        "author": {
          "firstName": "Tom",
          "lastName": "Coleman"
        },
        "votes": 2
      },
      {
        "title": "Welcome to Meteor",
        "author": {
          "firstName": "Sashko",
          "lastName": "Stubailo"
        },
        "votes": 3
      },
      {
        "title": "Advanced GraphQL",
        "author": {
          "firstName": "Sashko",
          "lastName": "Stubailo"
        },
        "votes": 1
      },
      {
        "title": "Launchpad is Cool",
        "author": {
          "firstName": "Mikhail",
          "lastName": "Novikov"
        },
        "votes": 7
      }
    ]
  }
}
```

</details>

**Comment by Peping** [comment] 2017-08-17 16:06
I think you misunderstood what 
> fieldA and fieldB must have identical field names

means. I'd wager it means that this wouldn't merge (i. e. not produce a single list in the result), because the lists have two different field names:
```graphql
query Posts {
    otherPosts: posts {
      title
      author {
        firstName
      }
    }
    posts {
      votes
      author {
        lastName
      }
    }
}
```

**Comment by fritz-gerneth** [comment] 2017-08-17 16:14
For the second comment: it is actually the other way around:
```
fragment conflictingBecauseAlias on Dog {
  name: nickname
  name
}
```
This is not possible. Your query is executable and valid. 

-----------

Just because Apollo behaves that way does't make it right. But you're right that the spec seems a bit unclear on that exact issue. Looking at the explanatory text below the algorithm the intention is still pretty clear - they may only be merged if they are semantically equivalent. But then I'm no authority either, so we could bring this to the GraphQL Team right away too :) 

The behavior you described does make sense in it own too though. Just saying the spec might already cover this :)

**Comment by Peping** [comment] 2017-08-17 16:21
> Your query is executable and valid.
Executable and valid and, most of all, _the two fields in the set will not merge_. I'll raise this issue in graphql github.

**Comment by fritz-gerneth** [comment] 2017-08-17 16:25
It will not merge because it doesn't cause any conflict due to the different names (that's what aliases are for).
For your query the result would be
```
posts {
    otherPosts: [{ ... }]
    posts: [{ ... }]
}
```

**Comment by Peping** [comment] 2017-08-17 16:29
... Which was exactly my intention. I meant this to serve as an example of what I thought the spec was really saying. I do not have an issue with this behavior.

**Comment by fritz-gerneth** [comment] 2017-08-17 16:32
No, the spec & this ticket is only about the behavior where fields have the same name in the result :) As soon as you alias the result of one field you can query the same field as often as you want with different parameters. 

E.g. no problem:
```
query Posts {
    byFirstName: posts {
      title
      author {
        firstName
      }
    }
    byLastName: posts {
      votes
      author {
        lastName
      }
    }
}
```

**Comment by Peping** [comment] 2017-08-17 16:38
I don't know if it's the heatwave over here causing me not to express myself clearly, but _I agree with you_. We've been in agreement for the past couple of comments. 
____________
The spec only talks about **whether two or more fields can merge**. It doesn't seem to say anything about **how to merge two or more fields** if the correct conditions are met. 

I think this is an oversight. I'm raising this issue over at https://github.com/graphql/graphql.github.io

**Closed** 2017-09-05 12:52 UTC
